apiVersion: v1
kind: Service
metadata:
  name: node-app-svc
spec:
  type: NodePort
  selector:
    app: node-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080